### ISSUE TITLE
ERROR: Failed building wheel for hidapi

### ISSUE THREAD

**Issue by mrbluecoat** [ElrondNetwork/ledger-elrond#11]
When running `pip3 install --user --upgrade --no-cache-dir ledgerblue` I got this error:

```
/bin/ld: cannot find -ludev
...
ERROR: Failed building wheel for hidapi
```

A little googling indicated I needed to run this command first: `sudo apt install -y libudev-dev`

Mentioning it here in case it helps others.

**Comment by mihaib79** [comment]
libudev-dev is already included in prepare-devenv line 17
