### ISSUE TITLE
Can't add data when sending eGLD via Elrond Ledger App => Can't delegate eGLD 

### ISSUE THREAD

**Issue by palnap** [ElrondNetwork/ledger-elrond#20]
Dunno if this is a Ledger app related issue or a wallet one but we can't add data using Wallet with Ledger authentication. It seems to be mandatory when sending to staking address.

Is it something planned ?

**Comment by palnap** [comment]
Sorry, didn't saw we needed to enable Contract Data in settings in the Ledger

**Comment by MauricioHernanCabrera** [comment]
@palnap I have the same problem, What is the solution?
![data-option](https://user-images.githubusercontent.com/30062028/194312953-380d362a-acb4-4d29-a62d-6f269692cd72.PNG)

**Comment by palnap** [comment]
Hi, just go the Elrond app on your ledger, go to settings and enable contract data.Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Mauricio Hernan Cabrera ***@***.***> Date : 06/10/2022  14:30  (GMT+01:00) À : ElrondNetwork/ledger-elrond ***@***.***> Cc : palnap ***@***.***>, Mention ***@***.***> Objet : Re: [ElrondNetwork/ledger-elrond] Can't add data when sending eGLD via Elrond Ledger App => Can't delegate eGLD  (#20) 
@palnap I have the same problem, What is the solution?
