### ISSUE TITLE
wallet doesn't detect running app on ledger

### ISSUE THREAD

**Issue by gballet** [ElrondNetwork/ledger-elrond#26]
I have installed the elrond app, and Ledger doesn't seem to work with my setup. I am running the app (reported as "pending ledger approval") and clicking on "connect ledger" at wallet.elrond.com. The wheel spins and after a while, it says it can not find the app. MyCrypto finds the ethereum wallet, so I'm sure the connection itself works.

App version: 1.0.3
Legder:
  Secure element: 1.6.0
  Microcontroller: 1.12
Browser: Mozilla Firefox 84.0 (64-bit)

No logs in the browser's console indicate any problem.

**Comment by drdelphi** [comment]
Hello,
You first need to update your Ledger's firmware to 1.6.1
After that you will be able to update your Elrond app to v1.0.6, which is compatible with web wallet.
Please keep us posted if you need further assistance.
Have a nice day and a happy new year !

**Comment by gballet** [comment]
Updating the app worked, thanks!
